### ISSUE TITLE
Check and possibly fix inheritance from Error (js)

### ISSUE THREAD

**Issue by ghost** [morpho-os/framework#252]
See
* https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work
* https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#use-returned-values-from-super-calls-as-this

**Comment by jackstr** [comment]
Continued in #100
